## numpy

#### 合併array
* np.r_ : 按列連接兩個矩陣,類似pandas中的concat()
* np.c_ : 按行連接兩個矩陣,類似pandas中的merge()

In [15]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.c_[a,b]

print("np.r_[%s,%s] : " %(a,b))
print(np.r_[a,b])
print('\n')
print("np.c_[%s,%s] : " %(a,b))
print(c)
print('\n')
print("np.c_[np.c_[%s,%s],%s] : " %(a,b,a))
print(np.c_[c,a])

np.r_[[1 2 3],[4 5 6]] : 
[1 2 3 4 5 6]


np.c_[[1 2 3],[4 5 6]] : 
[[1 4]
 [2 5]
 [3 6]]


np.c_[np.c_[[1 2 3],[4 5 6]],[1 2 3]] : 
[[1 4 1]
 [2 5 2]
 [3 6 3]]


#### 矩陣乘法
*   A.dot(B)

In [12]:
import numpy as np
A = np.array([[1],[2],[3]])
print("A = \n", A)
B = np.array([[1,2,3]])
print("B = \n", B)
print("A.dot(B) = \n", A.dot(B))

A = 
 [[1]
 [2]
 [3]]
B = 
 [[1 2 3]]
A.dot(B) = 
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


#### 維度變換

*   np.reshape(array, (i,j)) : 分成i列j行

In [5]:
import numpy as np
np.reshape(np.arange(15),(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 增加維度
*   np.newaxis : 放入[ , ]中，增加那個row或col的維度

In [7]:
import numpy as np
A = np.array([1,2,3,4])
print(A)
print("A[np.newaxis,:] 增加列的維度(0->1) \n" ,A[np.newaxis,:])
print("A.shape = " ,A[np.newaxis,:].shape)
print("A[:,np.newaxis] 增加行的維度(0->1) \n" ,A[:,np.newaxis])
print("A.shape = " ,A[:,np.newaxis].shape)


[1 2 3 4]
A[np.newaxis,:] 增加列的維度(0->1) 
 [[1 2 3 4]]
A.shape =  (1, 4)
A[:,np.newaxis] 增加行的維度(0->1) 
 [[1]
 [2]
 [3]
 [4]]
A.shape =  (4, 1)


### np.set_printoptions( 列印選項 )
[參考資料1](https://www.brilliantcode.net/1045/numpy-tutorial-how-to-print-array/)\
[參考資料2](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html)


Parameters
*   threshold : 元素門檻值 (default 1000)
*   precision : 浮點數列印精度 (default 8)
*   edgeitems : 省略列印內容時要顯示的元素數量 (default 3)
*   linewidth : 每一行要印出幾個字元 (default 75)
*   suppress  : 是否要抑制顯示小數位 (default False)
*   nanstr    : 當陣列元素值出現NaN時所顯示的字串 (default nan)
*   infstr    : 當陣列元素值出現inf時所顯示的字串 (default inf)
*   sign      : 控制正負號  (default ‘-‘)
*   formatter={ 使用lambda函數客製列印陣列元素的格式 }


* np.set_printoptions( threshold=元素門檻值 ) : NumPy預設值是1000。意思是如果陣列元素值沒有超過門檻值的話，NumPy就會讓Python將所有元素列印出來

In [9]:
import numpy as np
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
np.set_printoptions(threshold=20)
print("NumPy set_printoptions(threshold=20)\n", np.arange(20))
print()
# 陣列大小:20，門檻值15 => 陣列元素數量大於門檻值，應省略部分內容
np.set_printoptions(threshold=15)
print("NumPy set_printoptions(threshold=15)\n", np.arange(20))

NumPy set_printoptions(threshold=20)
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

NumPy set_printoptions(threshold=15)
 [ 0  1  2  3  4 ... 15 16 17 18 19]


* np.set_printoptions( precision=浮點數列印精度 ) : 控制陣列內容微幅點數時的列印精度(小數位數)，下列範例看得出來這個方法是會自動四捨五入

In [8]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## precision:控制陣列內容微幅點數時的列印精度(小數位數)
np.set_printoptions(precision=1)
print("NumPy set_printoptions(precision=1)\n", np.linspace(3, 5, 10))
print()
np.set_printoptions(precision=3)
print("NumPy set_printoptions(precision=3)\n", np.linspace(3, 5, 10))

NumPy set_printoptions(precision=1)
 [3.  3.2 3.4 3.7 3.9 4.1 4.3 4.6 4.8 5. ]

NumPy set_printoptions(precision=3)
 [3.    3.222 3.444 3.667 3.889 4.111 4.333 4.556 4.778 5.   ]


* np.set_printoptions( edgeitems=省略列印內容時要顯示的元素數量 )：當列印陣列時需要省略內容，edgeitems會決定要印出來的元素有幾個。

In [7]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## edgeitems:當列印陣列時需要省略內容，edgeitems會決定要印出來的元素有幾個
np.set_printoptions(threshold=10, edgeitems=3)
print("NumPy set_printoptions(edgeitems=3)\n", np.arange(15))
print()
np.set_printoptions(threshold=10, edgeitems=5)
print("NumPy set_printoptions(edgeitems=5)\n", np.arange(15))

NumPy set_printoptions(edgeitems=3)
 [ 0  1  2 ... 12 13 14]

NumPy set_printoptions(edgeitems=5)
 [ 0  1  2  3  4 ... 10 11 12 13 14]


* np.set_printoptions( linewidth=每一行要印出幾個字元 )：這只是單純決定列印陣列時每一行字的字元數上限，並不影響列印其他內容的每一行字元數上限

In [10]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## linewidth
np.set_printoptions(linewidth=10)
print("NumPy set_printoptions(linewidth=10)\n", np.arange(15))
print()
np.set_printoptions(linewidth=20)
print("NumPy set_printoptions(linewidth=25)\n", np.arange(15))

NumPy set_printoptions(linewidth=10)
 [ 0  1  2
  3  4  5
  6  7  8
  9 10 11
 12 13 14]

NumPy set_printoptions(linewidth=25)
 [ 0  1  2  3  4  5
  6  7  8  9 10 11
 12 13 14]


* np.set_printoptions( suppress=是否要抑制顯示小數位 )：

In [11]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
# suppress
np.set_printoptions(suppress=True)
print("NumPy set_printoptions(suppress=True)\n", np.arange(0, 1, 0.00001))
print()
np.set_printoptions(suppress=False)
print("NumPy set_printoptions(suppress=False)\n", np.arange(0, 1, 0.00001))

NumPy set_printoptions(suppress=True)
 [0. 0. 0. 0. 0. ...
 1. 1. 1. 1. 1.]

NumPy set_printoptions(suppress=False)
 [0.e+00 1.e-05
 2.e-05 3.e-05
 4.e-05 ... 1.e+00
 1.e+00 1.e+00
 1.e+00 1.e+00]


* np.set_printoptions( nanstr=當陣列元素值出現NaN時所顯示的字串 )：當陣列元素值出現not-a-number時要顯示的內容為何。

In [12]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## nanstr
# 當陣列元素值出現not-a-number時要顯示的內容為何
np.set_printoptions(nanstr="Oops!")
a = np.array([np.nan, 1, np.nan], dtype=np.float16)
print("NumPy set_printoptions(nanstr=\"Oops!\")\n", a)

NumPy set_printoptions(nanstr="Oops!")
 [Oops!    1. Oops!]


* np.set_printoptions( infstr=當陣列元素值出現inf時所顯示的字串 )：當陣列元素值出現inf(無限大)時要顯示的內容為何。

In [13]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## infstr
# 當陣列元素值出現inf(無限大)時要顯示的內容為何
np.set_printoptions(infstr="∞")
a = np.array([np.inf, 8, -np.inf])
print("NumPy set_printoptions(infstr=\"∞\")\n", a)

NumPy set_printoptions(infstr="∞")
 [    ∞    8.    -∞]


* np.set_printoptions( sign=控制正負號 )：當sign=’+’時，就會連正數都會加上正號；當sign=’-‘時(預設值)，就是只有數值<0時，才會加上負號

In [14]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## sign
# 當sign='+'時，就會連正數都會加上正號
np.set_printoptions(sign='+')
a = np.array([9, 8, -6, -7], dtype=np.float16)
print("NumPy set_printoptions(sign=\"+\")\n", a)
print()
# 當sign='-'時(預設值)，就是只有數值<0時，才會加上負號
np.set_printoptions(sign='-')
a = np.array([9, 8, -6, -7], dtype=np.float16)
print("NumPy set_printoptions(sign=\"-\")\n", a)

NumPy set_printoptions(sign="+")
 [+9. +8. -6. -7.]

NumPy set_printoptions(sign="-")
 [ 9.  8. -6. -7.]


* np.set_printoptions( formatter={ 使用lambda函數客製列印陣列元素的格式 } )：元素內容格式也能客製，甚至能在列印時改變數值\
型別關鍵字
    - all：各種型別都套用格式
    - float_kind：只套用floatxx
    - int_kind：只套用intxx
    - str_kind：只套用字串\

參考 : https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

In [24]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None)  # reset print options
## formatter
# 使用lambda函數客製列印陣列元素的格式
np.set_printoptions()  # reset print options
np.set_printoptions(formatter={'all': lambda x: 'i:' + str(x)})
print("NumPy set_printoptions(formatter={all: i:})\n", np.arange(0,5))
print()
# 這邊可以看出來，只設定了float的格式，是不會對int產生影響的
np.set_printoptions(formatter={'float_kind': lambda x: 'f:' + str(x)})
print("NumPy set_printoptions(formatter={float_kind: f:})\n", np.arange(0,5))
print("NumPy set_printoptions(formatter={float_kind: f:})\n", np.arange(0,5, dtype=np.float16))
print()
# 如果同時只想要客製float和int的格式，可以用逗號隔開設定值
np.set_printoptions(formatter={'int_kind': lambda x: 'i:' + str(x), 'float_kind': lambda x: 'f:' + str(x)})
print("NumPy set_printoptions({int_kind: i:, float_kind: f:})\n", np.arange(0,5))
print("NumPy set_printoptions({int_kind: i:, float_kind: f:})\n", np.arange(0,5, dtype=np.float16))

NumPy set_printoptions(formatter={all: i:})
 [i:0 i:1 i:2 i:3
 i:4]

NumPy set_printoptions(formatter={float_kind: f:})
 [0 1 2 3 4]
NumPy set_printoptions(formatter={float_kind: f:})
 [f:0.0 f:1.0 f:2.0
 f:3.0 f:4.0]

NumPy set_printoptions({int_kind: i:, float_kind: f:})
 [i:0 i:1 i:2 i:3
 i:4]
NumPy set_printoptions({int_kind: i:, float_kind: f:})
 [f:0.0 f:1.0 f:2.0
 f:3.0 f:4.0]
